### ISSUE TITLE
Maya errors

### ISSUE THREAD

**Issue by CGstunts** [Grackable/bear_core#1]
1. No Maya version supported is specified for Bear 1.3 

2. Upon running 
from bear.ui import Builder
Builder.mainUI()

I get the following error:
from bear.ui import Builder
Builder.mainUI()
# Error: ModuleNotFoundError: file <maya console> line 1: No module named 'bear'

Instructions state to create a folder named "bear" not "bear.ui"

Please help : )

Walter Schulz

**Comment by Grackable** [comment]
Hi Walter,

if a folder "bear" is the parent folder for all the BEAR files located in your default maya scripts folder, you can indeed call:

`from bear.ui import Builder`

So the "ui" folder and all the other folders and files should be located under "bear", which utimately allows you to call bear.ui.

Hope that helps and let me know if you need more support!

Best regards,

Gregor

**Comment by cranios** [comment]
Hi Walter,
I'm getting this error when I'm trying to generate a RIG Biped: version 1.3.1
(, line 269, in recreateComponent
# if int(bearVersion[0]) == 0:
# ValueError: invalid literal for int() with base 10: 'Core 1'
)
Maya 2024.2

Thks,
Daniel

**Comment by Grackable** [comment]
Perfect, thank you for reporting this bug, Daniel! This bug was introduced in 1.3.1 and has been fixed in 1.3.2.

**Comment by QuintonWoo** [comment]
Hello.. i'm receiving this error from maya.

from bear.ui import Builder
Builder.mainUI()
# Error: SyntaxError: file <maya console> line 1: invalid syntax # 

Downloaded the zip file from Git, extracted to maya scripts folder, pasted this "from bear.ui import Builder
Builder.mainUI()" into maya scripts python and received this error/

Maybe you can make an installation video.

**Comment by cranios** [comment]
> Perfeito, obrigado por reportar esse bug, Daniel! Esse bug foi introduzido na versão 1.3.1 e foi corrigido na versão 1.3.2.



> Perfect, thank you for reporting this bug, Daniel! This bug was introduced in 1.3.1 and has been fixed in 1.3.2.


**

> "Thanks for the quick report! Congratulations on the beautiful tool".

**

**Comment by Grackable** [comment]
Thank you for your message! An invalid syntax error usually refers to bad formatting or a typo. Are you sure you are executing it in a python script tab?

> Hello.. i'm receiving this error from maya.
> 
> from bear.ui import Builder Builder.mainUI()
> # Error: SyntaxError: file line 1: invalid syntax
> 
> Downloaded the zip file from Git, extracted to maya scripts folder, pasted this "from bear.ui import Builder Builder.mainUI()" into maya scripts python and received this error/
> 
> Maybe you can make an installation video.

**Comment by qhozen** [comment]
Thanks for the response. I believe I have done everything correctly but still an error. Here is a youtube link of the installation. https://youtu.be/hGrNrie4S_M

**Comment by Grackable** [comment]
Thanks, I will be more clear about this in the installation instructions. The problem that you have now is that the files are living in bear/bear_core-main instead of only bear. So you can remove the folder bear_core-main or copy bear_core-main directly to scripts and rename it to bear. Also you don't need to copy to the prefs folder. The prefs folder usually holds user data that is generated while using a script.

**Comment by qhozen** [comment]
Still no luck. I can import bear and import bear.ui, but when i try to import bear.ui.Builder I get a syntax error. No clue why. Here is a new video: https://youtu.be/LBzQaRTY988

**Comment by Grackable** [comment]
It looks like you need to upgrade your python package. BEAR requires python 3 which was introduced in Maya 2022. Upgrading python to version 3 in Maya 2020 seems to be doable:

How to Enable Python 3 in Maya 2020
Method 1: Using Environment Variable

    Close Maya.
    Set the following environment variable:
        Windows (Command Prompt or add to system environment variables):

set MAYA_PYTHON_VERSION=3

macOS/Linux (Terminal or add to .bashrc or .zshrc):

        export MAYA_PYTHON_VERSION=3

    Restart Maya, and it will use Python 3.7 instead of Python 2.

Method 2: Using Command-Line Flag

Run Maya with the -pythonver flag:

maya -pythonver 3

Limitations

    Python 3.7 Only: You cannot upgrade beyond Python 3.7 in Maya 2020.
    Incompatibility with Some Scripts: If your scripts rely on Python 2, they may break in Python 3.
    Maya 2022+ Recommended: If you need full, stable Python 3 support, upgrading to Maya 2022 or later is better since Python 3 is the default.
